# https://github.com/prisma/benching_setup/blob/master/setup_scripts/prisma-server/docker-compose.mysql.yml

version: '3'
services:
    db:
      image: mysql:5.7
      restart: always
      command: mysqld
      environment:
        MYSQL_USER: justinkim
        MYSQL_ROOT_PASSWORD: prisma
      ports:
      - "3306:3306"
      
#   prisma:
#     image: prismagraphql/prisma:${PRISMA_VERSION}
#     restart: always
#     ports:
#     - "4466:4466"
#     environment:
#       PRISMA_CONFIG: |
#         port: 4466
#         databases:
#           default:
#             connector: mysql
#             host: db
#             port: 3306
#             user: root
#             password: prisma
#             migrations: true